# Generated by Django 4.0.4 on 2022-05-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_percentage', models.IntegerField(default=0)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.IntegerField(choices=[(0, 'Non catégorisé'), (1, 'Revenus'), (2, 'Dépenses fixes'), (3, 'Salaires'), (4, 'Dividendes'), (5, 'Cotisations'), (6, 'Taxe et impôts'), (7, 'Autres')])),
                ('label', models.CharField(max_length=1000)),
            ],
        ),
    ]
