# Generated by Django 4.0.4 on 2022-05-17 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('category', models.IntegerField(choices=[(0, 'Non catégorisé'), (1, 'Revenus'), (2, 'Dépenses fixes'), (3, 'Salaires'), (4, 'Dividendes'), (5, 'Cotisations'), (6, 'Taxe et impôts'), (7, 'Autres')])),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.subcategory'),
        ),
    ]
