# Generated by Django 4.0.4 on 2022-05-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_subcategory_transaction_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.subcategory'),
        ),
    ]
