# Generated by Django 4.0.4 on 2022-05-19 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='total_amount',
        ),
    ]
